name: Continuous Integration Testing
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9.2]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9.2
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Run Tests
        working-directory: ./testing
        run: python3 -m unittest -v